### ISSUE TITLE
App developer documentation is not up to date

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/documentation#568]
This is a summary to track what needs to be done in order to improve/update the app developers documentation:

- [x] Remove container creation from basic app guide PR: #567
- [x] Update details on routes PR: #567
- [x] Update info.xml documentation PR: #567 

- [ ] Check dev env setup instructions #542
- [ ] App tutorial is broken #567
- [ ] New database migrations

## App integration docs
We should at least link to the documentation that apps provider to integrate with them

- [ ] Notifications
- [ ] Activity

## Frontend
- [ ] CSS/Frontend-Guidelines  #333 
- [ ] SCSS usage #355

I'm sure there is some stuff missing here. Feel free to add more. Of course any help is also welcome. Let's make it a great experience to get started with Nextcloud app development.

cc @nextcloud/documentation

**Comment by juliushaertl** [comment]
cc @Rello @te-online I think we also talked about the app documentation. Anything you were missing when getting started with app development?

**Comment by te-online** [comment]
Yes, I especially miss a thorough documentation for the frontend, mainly javascript. I use these docs http://vincentpetry.net/ocjsdocs/index.html a lot.

Also, for getting to know, how to do things, I often refer to the core apps, that are delivered with Nextcloud. But there seems to be no “best-practice” way, would love to see some thoughts on that, to skip learning the hard way about all the minor implications certain ways of doing things within Nextcloud can bring. (Like e.g. who do I include my app's js when the app is standalone/integrated into filelist/integrated into other stuff. There is a billions ways to do that, but none of them seem to be “standard”.)

**Comment by juliushaertl** [comment]
@te-online Good point, jsdoc should be added as well.

**Comment by MorrisJobke** [comment]
@juliushaertl What is the status here?

**Comment by juliushaertl** [comment]
There's still a lot to be done. Especially the app tutorial should be fixed, I'll see if i can go through the rest which i didn't cover in #567 for 14.

**Comment by MorrisJobke** [comment]
What is the status?

**Comment by juliushaertl** [comment]
Didn't have time for that yet. As always, help here is very welcome. :wink: 

I'd say we remove the milestone for now, since this is more a general thing we should approach.
