### ISSUE TITLE
New docs design improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/documentation#977]
Just some small possible design improvements of the beautiful new docs :sparkles: 

- [x] Logo takes a lot of space in the navigation, could be a bit smaller. #986
- [x] On hover/focus of the logo, it should change opacity instead of getting this background box. #986
- [ ] Is it possible to use Nunito as font? See files at https://github.com/nextcloud/server/tree/master/core/fonts
- [ ] Adjust button styles to be round like in Nextcloud, primary button in #0082c9
- [ ] There are 2 "Icons" entries in design guidelines
- [ ] The icons page has list layout, should be grid: https://docs.nextcloud.com/server/15/developer_manual/design/icons.html

**Comment by MorrisJobke** [comment]
> [ ] Logo takes a lot of space in the navigation, could be a bit smaller.

👍 cc @MariusBluem 



> * Is it possible to use Nunito as font?

We also had this idea, but I would really like to stick to the one shipped with the theme. It was chosen for a reason and we get fixes for that from upstream. Let's stick to the standard that is set by the theme creators.



> * [ ]  Adjust button styles to be round like in Nextcloud, primary button in #0082c9

Same as with the font: I would really like to stick to the default from the theme. Otherwise we end up in our own theme again. The style is used by so many documentations out there and totally fine in my opinion.

**Comment by MorrisJobke** [comment]
Basically this is the same discussion we have in the server with themes/theming app: changing the logo and color is fine - for the remaining stuff you should stick to the one that is shipped. It just makes maintainability easier.

**Comment by jancborchardt** [comment]
Hm, I mean changing the font is really not such a big modification, no? If there’s changed logos (via files) and colors (via CSS) already, we can also add ttf files and a section of CSS for the font? It’s just because epecially the heading font looks really different than our Nextcloud style.

**Comment by MorrisJobke** [comment]
I still think that this is fine. It’s the docs and not our main product. Changing it for the reason of just having everywhere the same font would then also be the same like changing the sidebar to our style because we use that also everywhere. IMO we should keep as much as possible as it is in the docs to not tweak on the docs and focus our efforts in the product or the content.

**Comment by jancborchardt** [comment]
> would then also be the same like changing the sidebar to our style because we use that also everywhere.

To be honest I would also prefer that. ;) I can understand that you would like to focus on the content, but for me showing the design docs to prospective designers, the design _is_ part of the content. :)

**Comment by skjnldsv** [comment]
> To be honest I would also prefer that. ;) I can understand that you would like to focus on the content, but for me showing the design docs to prospective designers, the design _is_ part of the content. :)

I understand your point. But the focus on a documentation is the content and the ease of use.
Let's leave it like that. This is maintainable ad finally we have something usable (and approved by a lot of people looking at the feedback and contribution we receive)
Let's change the logo size, do some small adjustments so it's not completely out of place and remind of nextcloud a bit, but keep it as simple as we can here.

**Comment by jancborchardt** [comment]
Fairphone for example uses the same docs software and theme, and they adjusted the typeface:
https://code.fairphone.com/projects/fp-osos/user/fairphone-open-source-os-installation-instructions.html

Looks instantly so much better. So let’s make a distinction here between "we don’t have time to work on it ourselves at the moment" and "this would be very nice to have and a contributor can pick it up". :wink:

**Comment by MorrisJobke** [comment]
> * [ ]  Logo takes a lot of space in the navigation, could be a bit smaller. #986
> * [ ]  On hover/focus of the logo, it should change opacity instead of getting this background box. #986

Both of them are fixed in #986

**Comment by MorrisJobke** [comment]
> Fairphone for example uses the same docs software and theme, and they adjusted the typeface:
> https://code.fairphone.com/projects/fp-osos/user/fairphone-open-source-os-installation-instructions.html

Actually I find it harder to read 🙈

**Comment by MorrisJobke** [comment]
> So let’s make a distinction here between "we don’t have time to work on it ourselves at the moment"

I was refering not to "we don't want to work on this", but rather at "we don't need to change everything always".
